language: ruby
services:
  - redis-server
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
addons:
  postgresql: '9.6'
before_script:
  - psql -c 'create database ppsps_project_test;' -U postgres
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - yarn run test
  - SECRET_KEY_BASE=a RAILS_ENV=production bundle exec rake assets:precompile
  - bundle exec rake spec:features
  - bundle exec rake spec:models
  - bundle exec rake spec:requests
  - bundle exec rake spec:mailers
env:
  secure: bCiY2/LZUxtkfzTqR/d3DFqmx2l+wmT/VVDoGgvMgSFjADnZt0GGauHd3Av4LEWagNuJxp9ldZPStEwpLdQEvIBf4gsUg3oAwYnlOpgWxRA6UEA6Lky+RMtRf8Cb9d/z/uhYnQbk2i383o9iOTV3A8B/f9RcR0fdU47KEAQVjqdy5WO1JvcJMbuPeyCsY8MgPrTn+1dSs5JFyVz2G1NqvoQylUKQDocHTHuzDHO4Qjj0/zcn358x/+zKZINJXMDTYCjAqo3rllJsTjL+1YhMnSxC4g6h0jpGRgZjQduHZ3JJ7zDJJfBdR8JOpyBQqkBKwiCOrI6QUdVvpmU7FX/rSxi1cNxdM4/TzrabyXOcbUiTNdlGGr2tMl8vO1mevlysZZY0RCxGvTtsHj/4rjLSMhzWMfgFn6Mi15y8prC7ESMnqDO9GLJ+qjqm5o20OnPXTfUsa5F3be9ZzpU0UIBm9BuFyPPaBKSeJR+FOj6dug5Y1E+/JKEB4MVIXMqhlcEtD1FmcLQSN8zT+dYjR3w3kIOPcJWfm+Mq27aOK8AIXZPs0VGiY2HIQPk7A9ddSIzJy/PUn18HhTzA0e0rAd7uu/La7mvCt9WESxwirnufPVZZcsfBWXjAyU4FS34ZodYB6Wj1M97LzfZ1JTEKzc9JDj7YoFF/PhrcsHPo0XkS4kA=
